### ISSUE TITLE
Setup linting and/or code styling

### ISSUE THREAD

**Issue by prowe** [sourceallies/jest-mock-component#1]
Maybe just prettier.
TS lint?

**Comment by prowe** [comment]
Need to also make sure we have a vscode extension installed in the dev container

**Comment by kmcgill88** [comment]
TS Lint is actually deprecated in favor of [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint).

**Comment by prowe** [comment]
I always forget about that.  Maybe just prettier will do. Just something to keep s white space consistent?
